---
- name: Create sudo group
  hosts: all
  gather_facts: no
  vars:
    sudo_group: default-sudo

  tasks:
    - name: Calling role to create sudo group
      include_role:
        name: sudo-group-role